### PR TITLE
Remap 1.14 enchantments

### PR DESCRIPTION
**Pull request by KennyTV**

### CODE REVIEW

**Comment by ForceUpdate1** [comment]
http://paste.cytooxien.de/semotakeva.cs

**Comment by KennyTV** [comment]
Oof, that's your code, prolly needs a bit refactoring 👀 Will do that later

**Comment by KennyTV** [comment]
@ForceUpdate1 plz test

**Comment by ForceUpdate1** [comment]
@KennyTV 
It looks good
https://i.imgur.com/RdgB2to.png

**Comment by ForceUpdate1** [comment]
@KennyTV 
It looks good in the 1.13.2
https://i.imgur.com/uII9azX.png

In 1.12.2 the enchantment effect is missing.

**Comment by ForceUpdate1** [comment]
Works perfectly.
I love you ❤

**Comment by Matsv** [comment]
Thanks ❤️❤️

**Pull request merged**
