### PR TITLE
1.16.4 pre1

### PR DESCRIPTION
**Pull request by KennyTV**
Random piece of trivia; clientbound hotbar change uses a byte, serverbound a short :thonkjang:

### CODE REVIEW

**Comment by Gerrygames** [comment]
I think the selected slot should only be updated by the serverbound packet. The reason mojang changed this is probably because an open book packet might arrive when the server has changed the selected slot. Client wants to open book on hotbar slot 0 -> server changes selected hotbar slot to 1 -> server receives open book packet and tries to open book on slot 1.
Also might wanna look into if the client ever changes the selected slot without sending a packet (respawn?).

**Comment by KennyTV** [comment]
That would break plugins changing the client's slot (to set and open a book in a specific hotbar slot for whatever reason, or more likely people cancelling the hotbar change). For respawns, the client luckily sends a serverbound packet setting the slot to 0

**Comment by Gerrygames** [comment]
Doesn't the client send a confirmation when the hotbar slot is changed via the clientbound packet?

**Comment by KennyTV** [comment]
Oh right, thank you, changed it

**Review by Gerrygames — APPROVED** [review]

**Pull request merged**
