### PR TITLE
Add missing translation mappings and component rewriter

### PR DESCRIPTION
**Pull request by FlorianMichael**
Components are still a huge mess but atleast no mappings are missing (at least important one's) and missing component rewriters are added, next step would be to use them everywhere correctly and to add AbstractProtocol#getComponentRewriter.

### CODE REVIEW

**Comment by FlorianMichael** [comment]
image
Fixes shulker box title not being remapped (1.10 client and 1.12 server), also want to remove my temporary fix for it:
https://github.com/ViaVersion/ViaRewind/blob/740a6d9b9617815dff3e39b170d0d868e0873d81/common/src/main/java/com/viaversion/viarewind/protocol/v1_9to1_8/rewriter/BlockItemPacketRewriter1_9.java#L88 as well as some cursed jank in ViaRewind's chat util

**Comment by Kichura** [comment]
> image
> Fixes shulker box title not being remapped (1.10 client and 1.12 server), also want to remove my temporary fix for it: https://github.com/ViaVersion/ViaRewind/blob/740a6d9b9617815dff3e39b170d0d868e0873d81/common/src/main/java/com/viaversion/viarewind/protocol/v1_9to1_8/rewriter/BlockItemPacketRewriter1_9.java#L88
> 
> as well as some cursed jank in ViaRewind's chat util

Have you also checked the other GUIs such as Hoppers, Chests, etc? *(asking out of curiosity)*

**Comment by FlorianMichael** [comment]
No because shulker is the only GUI being added in the versions I fixed, in theory we would need all rewriters in open screen packets as well, but it's not worth it.

**Comment by FlorianMichael** [comment]
Also build errors can be ignored I believe and are only because of version desyncs.

**Review by kennytv — APPROVED** [review]

**Pull request merged**
