### PR TITLE
[WIP] Add 1.14.x support, some 1.13.x fixes

### PR DESCRIPTION
**Pull request by ForceUpdate1**
Progess:  █████████░░░░░░ 60%

TODO 

**Block remaps:**:
- [x] scaffolding
- [x] bell
- [x] campfire
- [x] lectern
- [x] grindstone
- [x] stonecutter
- [ ] jigsaw
- [x] loom
- [x] sweet berry bush

**Inventory rewrites**:
- [x] cartography_table
- [x] blast_furnace
- [x] smoker
- [x] grindstone
- [ ] stonecutter
- [x] ~~jigsaw ?~~
- [ ] loom ?

**Item remaps**:
- [x] all new Items
- [x]  + crossbow
- [x]  + suspicious_stew

**Also**:
- [x] improve lighting
- [x] inventory name remap
- [x] fix young bamboo plants will not remap
- [ ] remap new 1.14 enchantments

**Entity**:
- [x] ZombieVillager are invisible
- [ ] 1.13->1.12 Particle rewrite

### CODE REVIEW

**Comment by ForceUpdate1** [comment]
TODO:

[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 747
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 712
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 699
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 726
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 741
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 722
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 747
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 712
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 699
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 726
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 741
[17:00:53] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 722
[17:00:54] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 730
[17:00:54] [Netty Epoll Server IO #3/WARN]: [ViaBackwards] Missing 1.13.2 item for 1.14 item 730

**Comment by KennyTV** [comment]
^✔

**Comment by ForceUpdate1** [comment]
Thank you ❤

**Comment by ForceUpdate1** [comment]
2019-06-07 at 18:58:58.058 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9122
2019-06-07 at 18:58:58.103 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9122
2019-06-07 at 18:58:58.150 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9122
2019-06-07 at 18:58:58.184 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9124
2019-06-07 at 18:58:58.265 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9126
2019-06-07 at 18:58:58.312 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9127
2019-06-07 at 18:59:06.428 [Netty Epoll Server IO #3] WARN  us.myles.ViaVersion.ViaVersionPlugin - [ViaVersion] Missing 1.14 blockstate for 1.13.2 blockstate 9124

**Comment by Gerrygames** [comment]
1.14 enchantments are not remapped yet

**Pull request merged**
