### PR TITLE
Fix display entities for pre 1.19.4 clients

### PR DESCRIPTION
**Pull request by GliczDev**
TODO:
- [x] Fix text display
- [x] Fix item display
- [ ] Fix block display 
- [ ] Transformation (only translation) support
- [ ] Interpolation delay and duration support (might be moved into another PR)

### CODE REVIEW

**Comment by GliczDev** [comment]
If you have any idea how can i set block for a falling block using metadata, please let me know

**Comment by GliczDev** [comment]
When I change rewriting block display from falling block to armor stand, it shows, any idea why???

**Comment by tomcraft** [comment]
The falling block entity doesn't use the metadata system to define its blockstate.
One idea would be to cancel the spawn packet and send a falling block spawn when you receive the blockstate metadata.

**Comment by GliczDev** [comment]
Okay, but how can I send a falling block spawn

**Comment by tomcraft** [comment]
You have to build the packet from scratch using PacketWrapper. I think you can find some examples in other places of the source-code.

**Comment by GliczDev** [comment]
Okay, but now, how can I get metadata in spawn entity handler

**Comment by GliczDev** [comment]
Unfortunately i still don't know how to do this, I won't find solution, I'll just leave it without block display fix

**Comment by GliczDev** [comment]
Finally, I almost fixed block display, but I don't know how can I set and read metadata in spawn entity packet handler

**Comment by GliczDev** [comment]
Also, display entities have `0.5` 'added' to x and z position, and when I add it to this falling block, after some time it removes this position change
```java
wrapper.set(Type.DOUBLE, 0, wrapper.get(Type.DOUBLE, 0) + 0.5);
wrapper.set(Type.DOUBLE, 2, wrapper.get(Type.DOUBLE, 2) + 0.5);
```

**Comment by GliczDev** [comment]
As I see, entity meta is sent after spawn entity, so idk how can I finish fixing block display entity

**Comment by GliczDev** [comment]
I totally forgot about this PR because of problems I had, I can try to finish it

**Comment by FlorianMichael** [comment]
(Mostly) Superseded by https://github.com/ViaVersion/ViaBackwards/pull/871

**Pull request closed without merging**
